---
- name: check bgp json
  shell: "net json"
  register: command_output
  ignore_errors: yes
  become: yes
- local_action: copy content={{ command_output.stdout_lines | to_nice_json }} dest=ztp_verifybgp
  ignore_errors: yes
